[supabase]
url = "https://rbflzmvyzldbvshbtqvx.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJiZmx6bXZ5emxkYnZzaGJ0cXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMDkyNDIsImV4cCI6MjA2NTY4NTI0Mn0.ndn9vs5boCgAxRWdpdPI8A-t1uQXtIspWNufNpk1g9Y"

[app]
use_supabase = true
